import InsacermoActionabilityInformation.InfiniteHorizonActionability
import Mathlib.Topology.MetricSpace.Contracting

namespace InsacermoActionabilityInformation

/-- The nonnegative contraction constant associated with a nonnegative real
discount factor. -/
def discountNNReal (gamma : ℝ) (hgamma0 : 0 ≤ gamma) : NNReal :=
  ⟨gamma, hgamma0⟩

@[simp] theorem coe_discountNNReal (gamma : ℝ) (hgamma0 : 0 ≤ gamma) :
    ((discountNNReal gamma hgamma0 : NNReal) : ℝ) = gamma := rfl

/-- The already-proved pointwise Bellman contraction upgrades to mathlib's
`LipschitzWith` statement on the complete finite-product sup metric. -/
theorem infiniteBellman_lipschitzWith
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) :
    LipschitzWith (discountNNReal gamma hgamma0)
      (infiniteBellman P stageCost gamma) := by
  apply LipschitzWith.of_dist_le_mul
  intro V W
  apply (dist_pi_le_iff').2
  intro x
  have hpoint : ∀ y, |V y - W y| ≤ dist V W := by
    intro y
    simpa [Real.dist_eq] using (dist_le_pi_dist V W y)
  have h := infiniteBellman_uniform_close P stageCost gamma (dist V W)
    hgamma0 V W hpoint x
  simpa [Real.dist_eq] using h

/-- For `0 <= gamma < 1`, the finite-state discounted Bellman operator is a
contracting self-map in mathlib's Banach fixed-point sense. -/
theorem infiniteBellman_contractingWith
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1) :
    ContractingWith (discountNNReal gamma hgamma0)
      (infiniteBellman P stageCost gamma) := by
  refine ⟨?_, infiniteBellman_lipschitzWith P stageCost gamma hgamma0⟩
  exact_mod_cast hgamma1

/-- Canonical Banach fixed point of the discounted Bellman operator. -/
noncomputable def infiniteBellmanFixedPoint
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1) : X → ℝ :=
  ContractingWith.fixedPoint
    (infiniteBellman P stageCost gamma)
    (infiniteBellman_contractingWith P stageCost gamma hgamma0 hgamma1)

/-- The canonical Banach point satisfies the Bellman fixed-point equation. -/
theorem infiniteBellmanFixedPoint_isFixedPoint
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1) :
    InfiniteBellmanFixedPoint P stageCost gamma
      (infiniteBellmanFixedPoint P stageCost gamma hgamma0 hgamma1) := by
  have hfix := ContractingWith.fixedPoint_isFixedPt
    (infiniteBellman_contractingWith P stageCost gamma hgamma0 hgamma1)
  intro x
  exact congrFun hfix x

/-- Existence of an infinite-horizon discounted Bellman fixed point under the
frozen finite-state assumptions. -/
theorem infiniteBellman_fixedPoint_exists
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1) :
    ∃ Vstar : X → ℝ, InfiniteBellmanFixedPoint P stageCost gamma Vstar := by
  exact ⟨infiniteBellmanFixedPoint P stageCost gamma hgamma0 hgamma1,
    infiniteBellmanFixedPoint_isFixedPoint P stageCost gamma hgamma0 hgamma1⟩

/-- The discounted finite-state Bellman fixed point exists and is unique. -/
theorem infiniteBellman_fixedPoint_existsUnique
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1) :
    ∃! Vstar : X → ℝ, InfiniteBellmanFixedPoint P stageCost gamma Vstar := by
  refine ⟨infiniteBellmanFixedPoint P stageCost gamma hgamma0 hgamma1,
    infiniteBellmanFixedPoint_isFixedPoint P stageCost gamma hgamma0 hgamma1, ?_⟩
  intro W hW
  exact infiniteBellman_fixedPoint_unique P stageCost gamma hgamma0 hgamma1
    hW (infiniteBellmanFixedPoint_isFixedPoint P stageCost gamma hgamma0 hgamma1)

/-- The canonical infinite-horizon optimal-action contract is now generated by
an actually proved fixed point rather than by a supplied candidate value. -/
def CanonicalInfiniteBellmanGood
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1) : X → A → Prop :=
  InfiniteBellmanGood P stageCost gamma
    (infiniteBellmanFixedPoint P stageCost gamma hgamma0 hgamma1)

/-- Canonical infinite-horizon actionability is the frozen `SafeRep` kernel
instantiated by the proved Banach fixed point. -/
def CanonicalInfiniteBellmanSafeRep
    {X A Y : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1)
    (B : Set X) (C : Set A) (h : X → Y) : Prop :=
  SafeRep (CanonicalInfiniteBellmanGood P stageCost gamma hgamma0 hgamma1) B C h

/-- Full-state/full-capability identity representation is actionable for the
canonical infinite-horizon contract. -/
theorem canonicalInfiniteBellmanSafeRep_identity_univ
    {X A : Type*} [Fintype X] [Nonempty X] [Fintype A] [Nonempty A]
    (P : X → A → FiniteLaw X)
    (stageCost : X → A → ℝ)
    (gamma : ℝ) (hgamma0 : 0 ≤ gamma) (hgamma1 : gamma < 1)
    (B : Set X) :
    CanonicalInfiniteBellmanSafeRep P stageCost gamma hgamma0 hgamma1
      B Set.univ id := by
  simpa [CanonicalInfiniteBellmanSafeRep, CanonicalInfiniteBellmanGood,
    InfiniteBellmanSafeRep] using
    (infiniteBellmanSafeRep_identity_univ P stageCost gamma
      (infiniteBellmanFixedPoint P stageCost gamma hgamma0 hgamma1) B)

end InsacermoActionabilityInformation
