import InsacermoActionabilityInformation.StructuralAuditSCCBridge
import Mathlib.Logic.Relation

namespace InsacermoActionabilityInformation

namespace StructuralAuditReachability

open TemporalJointContractComplex
open TemporalObstructionPersistence
open StructuralAuditSCCBridge

/-- State-valued goals are available exactly at the state that names them. -/
def SingletonAvail {X : Type*} (x : X) : Set X := {x}

/-- Ordinary directed reachability generated by the one-step dynamics. -/
def StateReachable {X : Type*} (Step : X → X → Prop) (x y : X) : Prop :=
  Relation.ReflTransGen Step x y

/-- Mutual reachability, i.e. the strongly-connected-component equivalence
relation generated by the directed dynamics. -/
def SameSCC {X : Type*} (Step : X → X → Prop) (x y : X) : Prop :=
  StateReachable Step x y ∧ StateReachable Step y x

theorem sameSCC_refl
    {X : Type*} {Step : X → X → Prop} (x : X) :
    SameSCC Step x x := by
  exact ⟨Relation.ReflTransGen.refl, Relation.ReflTransGen.refl⟩

theorem sameSCC_symm
    {X : Type*} {Step : X → X → Prop} {x y : X}
    (h : SameSCC Step x y) :
    SameSCC Step y x := by
  exact ⟨h.2, h.1⟩

theorem sameSCC_trans
    {X : Type*} {Step : X → X → Prop} {x y z : X}
    (hxy : SameSCC Step x y) (hyz : SameSCC Step y z) :
    SameSCC Step x z := by
  constructor
  · exact Relation.ReflTransGen.trans hxy.1 hyz.1
  · exact Relation.ReflTransGen.trans hyz.2 hxy.2

/-- In a finite pairwise-comparable family for a transitive reflexive
reachability relation, there is a source goal that reaches every goal in the
family. -/
theorem exists_reach_source_of_pairwise
    {X : Type*} [DecidableEq X]
    {Step : X → X → Prop}
    {F : Finset X}
    (hne : F.Nonempty)
    (hpair : PairwiseComparableOn (StateReachable Step) F) :
    ∃ q, q ∈ F ∧ ∀ r, r ∈ F → StateReachable Step q r := by
  classical
  induction F using Finset.induction_on with
  | empty =>
      simp at hne
  | @insert a s ha ih =>
      by_cases hs : s = ∅
      · subst s
        refine ⟨a, by simp, ?_⟩
        intro r hr
        have hra : r = a := by simpa using hr
        subst r
        exact Relation.ReflTransGen.refl
      · have hsne : s.Nonempty := Finset.nonempty_iff_ne_empty.mpr hs
        have hpairS : PairwiseComparableOn (StateReachable Step) s := by
          intro q hq r hr hqr
          exact hpair q (Finset.mem_insert_of_mem hq)
            r (Finset.mem_insert_of_mem hr) hqr
        rcases ih hsne hpairS with ⟨m, hm, hmall⟩
        have ham_ne : a ≠ m := by
          intro ham
          subst m
          exact ha hm
        have hcomp :
            StateReachable Step a m ∨ StateReachable Step m a :=
          hpair a (by simp) m (Finset.mem_insert_of_mem hm) ham_ne
        rcases hcomp with ham | hma
        · refine ⟨a, by simp, ?_⟩
          intro r hr
          rcases Finset.mem_insert.mp hr with rfl | hrs
          · exact Relation.ReflTransGen.refl
          · exact Relation.ReflTransGen.trans ham (hmall r hrs)
        · refine ⟨m, Finset.mem_insert_of_mem hm, ?_⟩
          intro r hr
          rcases Finset.mem_insert.mp hr with rfl | hrs
          · exact hma
          · exact hmall r hrs

/-- Every state-goal that is jointly recoverable along one common trajectory
is reachable from the initial state in the reflexive-transitive closure of
Step. -/
theorem jointRecoverable_singletonAvail_implies_reachable
    {X : Type*} {Step : X → X → Prop} :
    ∀ H x {R : Set X},
      JointRecoverable SingletonAvail Step H x R →
      ∀ q, q ∈ R → StateReachable Step x q := by
  intro H
  induction H with
  | zero =>
      intro x R hjoint q hq
      have hqx : q = x := by
        simpa [SingletonAvail] using hjoint hq
      subst q
      exact Relation.ReflTransGen.refl
  | succ n ih =>
      intro x R hjoint q hq
      rcases hjoint with hnow | ⟨y, hxy, hrest⟩
      · have hqx : q = x := by
          simpa [SingletonAvail] using hnow hq
        subst q
        exact Relation.ReflTransGen.refl
      · by_cases hqx : q = x
        · subst q
          exact Relation.ReflTransGen.refl
        · have hqrest : q ∈ R \ SingletonAvail x := by
            refine ⟨hq, ?_⟩
            simpa [SingletonAvail] using hqx
          exact Relation.ReflTransGen.head hxy
            (ih y hrest q hqrest)

/-- One common joint-recovery trajectory linearly orders every pair of
distinct state-valued goals by eventual reachability. -/
theorem jointRecoverable_singletonAvail_implies_pairwiseComparable
    {X : Type*} {Step : X → X → Prop} :
    ∀ H x {R : Set X},
      JointRecoverable SingletonAvail Step H x R →
      ∀ q, q ∈ R → ∀ r, r ∈ R → q ≠ r →
        (StateReachable Step q r ∨ StateReachable Step r q) := by
  intro H
  induction H with
  | zero =>
      intro x R hjoint q hq r hr hqr
      have hqx : q = x := by
        simpa [SingletonAvail] using hjoint hq
      have hrx : r = x := by
        simpa [SingletonAvail] using hjoint hr
      subst q
      subst r
      exact False.elim (hqr rfl)
  | succ n ih =>
      intro x R hjoint q hq r hr hqr
      rcases hjoint with hnow | ⟨y, hxy, hrest⟩
      · have hqx : q = x := by
          simpa [SingletonAvail] using hnow hq
        have hrx : r = x := by
          simpa [SingletonAvail] using hnow hr
        subst q
        subst r
        exact False.elim (hqr rfl)
      · by_cases hqx : q = x
        · subst q
          have hrx : r ≠ x := by
            intro hrx
            subst r
            exact hqr rfl
          have hrrest : r ∈ R \ SingletonAvail x := by
            refine ⟨hr, ?_⟩
            simpa [SingletonAvail] using hrx
          have hyr : StateReachable Step y r :=
            jointRecoverable_singletonAvail_implies_reachable
              n y hrest r hrrest
          exact Or.inl (Relation.ReflTransGen.head hxy hyr)
        · by_cases hrx : r = x
          · subst r
            have hqrest : q ∈ R \ SingletonAvail x := by
              refine ⟨hq, ?_⟩
              simpa [SingletonAvail] using hqx
            have hyq : StateReachable Step y q :=
              jointRecoverable_singletonAvail_implies_reachable
                n y hrest q hqrest
            exact Or.inr (Relation.ReflTransGen.head hxy hyq)
          · have hqrest : q ∈ R \ SingletonAvail x := by
              refine ⟨hq, ?_⟩
              simpa [SingletonAvail] using hqx
            have hrrest : r ∈ R \ SingletonAvail x := by
              refine ⟨hr, ?_⟩
              simpa [SingletonAvail] using hrx
            exact ih y hrest q hqrest r hrrest hqr

/-- Necessity half of the SCC-chain characterization for the existing
INSACERMO joint-recovery semantics. -/
theorem eventual_stateGoal_feasible_implies_chain
    {X : Type*} [DecidableEq X]
    {Step : X → X → Prop}
    {x : X} {F : Finset X}
    (hfinite :
      HasFiniteJointRecoveryDepth SingletonAvail Step x F) :
    (∀ q, q ∈ F → StateReachable Step x q) ∧
      PairwiseComparableOn (StateReachable Step) F := by
  rcases hfinite with ⟨H, hH⟩
  constructor
  · intro q hq
    exact jointRecoverable_singletonAvail_implies_reachable
      H x hH q hq
  · intro q hq r hr hqr
    exact jointRecoverable_singletonAvail_implies_pairwiseComparable
      H x hH q hq r hr hqr

end StructuralAuditReachability

end InsacermoActionabilityInformation
