import InsacermoActionabilityInformation.StructuralAuditSCCBridge
import Mathlib.Logic.Relation

namespace InsacermoActionabilityInformation

namespace StructuralAuditReachability

open TemporalJointContractComplex
open TemporalObstructionPersistence
open StructuralAuditSCCBridge

/-- State-valued goals are available exactly at the state that names them. -/
def SingletonAvail {X : Type*} (x : X) : Set X := {x}

/-- Ordinary directed reachability generated by the one-step dynamics. -/
def StateReachable {X : Type*} (Step : X → X → Prop) (x y : X) : Prop :=
  Relation.ReflTransGen Step x y

/-- Mutual reachability, i.e. the strongly-connected-component equivalence
relation generated by the directed dynamics. -/
def SameSCC {X : Type*} (Step : X → X → Prop) (x y : X) : Prop :=
  StateReachable Step x y ∧ StateReachable Step y x

theorem sameSCC_refl
    {X : Type*} {Step : X → X → Prop} (x : X) :
    SameSCC Step x x := by
  exact ⟨Relation.ReflTransGen.refl, Relation.ReflTransGen.refl⟩

theorem sameSCC_symm
    {X : Type*} {Step : X → X → Prop} {x y : X}
    (h : SameSCC Step x y) :
    SameSCC Step y x := by
  exact ⟨h.2, h.1⟩

theorem sameSCC_trans
    {X : Type*} {Step : X → X → Prop} {x y z : X}
    (hxy : SameSCC Step x y) (hyz : SameSCC Step y z) :
    SameSCC Step x z := by
  constructor
  · exact Relation.ReflTransGen.trans hxy.1 hyz.1
  · exact Relation.ReflTransGen.trans hyz.2 hxy.2

/-- In a finite pairwise-comparable family for a transitive reflexive
reachability relation, there is a source goal that reaches every goal in the
family. -/
theorem exists_reach_source_of_pairwise
    {X : Type*} [DecidableEq X]
    {Step : X → X → Prop}
    {F : Finset X}
    (hne : F.Nonempty)
    (hpair : PairwiseComparableOn (StateReachable Step) F) :
    ∃ q, q ∈ F ∧ ∀ r, r ∈ F → StateReachable Step q r := by
  classical
  induction F using Finset.induction_on with
  | empty =>
      simp at hne
  | @insert a s ha ih =>
      by_cases hs : s = ∅
      · subst s
        refine ⟨a, by simp, ?_⟩
        intro r hr
        have hra : r = a := by simpa using hr
        subst r
        exact Relation.ReflTransGen.refl
      · have hsne : s.Nonempty := Finset.nonempty_iff_ne_empty.mpr hs
        have hpairS : PairwiseComparableOn (StateReachable Step) s := by
          intro q hq r hr hqr
          exact hpair q (Finset.mem_insert_of_mem hq)
            r (Finset.mem_insert_of_mem hr) hqr
        rcases ih hsne hpairS with ⟨m, hm, hmall⟩
        have ham_ne : a ≠ m := by
          intro ham
          subst m
          exact ha hm
        have hcomp :
            StateReachable Step a m ∨ StateReachable Step m a :=
          hpair a (by simp) m (Finset.mem_insert_of_mem hm) ham_ne
        rcases hcomp with ham | hma
        · refine ⟨a, by simp, ?_⟩
          intro r hr
          rcases Finset.mem_insert.mp hr with rfl | hrs
          · exact Relation.ReflTransGen.refl
          · exact Relation.ReflTransGen.trans ham (hmall r hrs)
        · refine ⟨m, Finset.mem_insert_of_mem hm, ?_⟩
          intro r hr
          rcases Finset.mem_insert.mp hr with rfl | hrs
          · exact hma
          · exact hmall r hrs

/-- Every state-goal that is jointly recoverable along one common trajectory
is reachable from the initial state in the reflexive-transitive closure of
Step. -/
theorem jointRecoverable_singletonAvail_implies_reachable
    {X : Type*} {Step : X → X → Prop} :
    ∀ H x {R : Set X},
      JointRecoverable SingletonAvail Step H x R →
      ∀ q, q ∈ R → StateReachable Step x q := by
  intro H
  induction H with
  | zero =>
      intro x R hjoint q hq
      have hqx : q = x := by
        simpa [SingletonAvail] using hjoint hq
      subst q
      exact Relation.ReflTransGen.refl
  | succ n ih =>
      intro x R hjoint q hq
      rcases hjoint with hnow | ⟨y, hxy, hrest⟩
      · have hqx : q = x := by
          simpa [SingletonAvail] using hnow hq
        subst q
        exact Relation.ReflTransGen.refl
      · by_cases hqx : q = x
        · subst q
          exact Relation.ReflTransGen.refl
        · have hqrest : q ∈ R \ SingletonAvail x := by
            refine ⟨hq, ?_⟩
            simpa [SingletonAvail] using hqx
          exact Relation.ReflTransGen.head hxy
            (ih y hrest q hqrest)

/-- One common joint-recovery trajectory linearly orders every pair of
distinct state-valued goals by eventual reachability. -/
theorem jointRecoverable_singletonAvail_implies_pairwiseComparable
    {X : Type*} {Step : X → X → Prop} :
    ∀ H x {R : Set X},
      JointRecoverable SingletonAvail Step H x R →
      ∀ q, q ∈ R → ∀ r, r ∈ R → q ≠ r →
        (StateReachable Step q r ∨ StateReachable Step r q) := by
  intro H
  induction H with
  | zero =>
      intro x R hjoint q hq r hr hqr
      have hqx : q = x := by
        simpa [SingletonAvail] using hjoint hq
      have hrx : r = x := by
        simpa [SingletonAvail] using hjoint hr
      subst q
      subst r
      exact False.elim (hqr rfl)
  | succ n ih =>
      intro x R hjoint q hq r hr hqr
      rcases hjoint with hnow | ⟨y, hxy, hrest⟩
      · have hqx : q = x := by
          simpa [SingletonAvail] using hnow hq
        have hrx : r = x := by
          simpa [SingletonAvail] using hnow hr
        subst q
        subst r
        exact False.elim (hqr rfl)
      · by_cases hqx : q = x
        · subst q
          have hrx : r ≠ x := by
            intro hrx
            subst r
            exact hqr rfl
          have hrrest : r ∈ R \ SingletonAvail x := by
            refine ⟨hr, ?_⟩
            simpa [SingletonAvail] using hrx
          have hyr : StateReachable Step y r :=
            jointRecoverable_singletonAvail_implies_reachable
              n y hrest r hrrest
          exact Or.inl (Relation.ReflTransGen.head hxy hyr)
        · by_cases hrx : r = x
          · subst r
            have hqrest : q ∈ R \ SingletonAvail x := by
              refine ⟨hq, ?_⟩
              simpa [SingletonAvail] using hqx
            have hyq : StateReachable Step y q :=
              jointRecoverable_singletonAvail_implies_reachable
                n y hrest q hqrest
            exact Or.inr (Relation.ReflTransGen.head hxy hyq)
          · have hqrest : q ∈ R \ SingletonAvail x := by
              refine ⟨hq, ?_⟩
              simpa [SingletonAvail] using hqx
            have hrrest : r ∈ R \ SingletonAvail x := by
              refine ⟨hr, ?_⟩
              simpa [SingletonAvail] using hrx
            exact ih y hrest q hqrest r hrrest hqr

/-- Necessity half of the SCC-chain characterization for the existing
INSACERMO joint-recovery semantics. -/
theorem eventual_stateGoal_feasible_implies_chain
    {X : Type*} [DecidableEq X]
    {Step : X → X → Prop}
    {x : X} {F : Finset X}
    (hfinite :
      HasFiniteJointRecoveryDepth SingletonAvail Step x F) :
    (∀ q, q ∈ F → StateReachable Step x q) ∧
      PairwiseComparableOn (StateReachable Step) F := by
  rcases hfinite with ⟨H, hH⟩
  constructor
  · intro q hq
    exact jointRecoverable_singletonAvail_implies_reachable
      H x hH q hq
  · intro q hq r hr hqr
    exact jointRecoverable_singletonAvail_implies_pairwiseComparable
      H x hH q hq r hr hqr


/-- Adding the current state as a state-valued goal does not increase the
required horizon: if the residual bundle is jointly recoverable from q, then
the bundle obtained by also requiring q is jointly recoverable from q at the
same horizon. -/
theorem jointRecoverable_insert_current
    {X : Type*} {Step : X → X → Prop}
    {H : ℕ} {q : X} {R : Set X}
    (hR : JointRecoverable SingletonAvail Step H q R) :
    JointRecoverable SingletonAvail Step H q (Set.insert q R) := by
  cases H with
  | zero =>
      intro z hz
      rcases hz with rfl | hzR
      · simp [SingletonAvail]
      · have hzq : z = q := by
          simpa [SingletonAvail] using hR hzR
        subst z
        simp [SingletonAvail]
  | succ n =>
      rcases hR with hnow | ⟨y, hqy, hrest⟩
      · exact Or.inl (by
          intro z hz
          rcases hz with rfl | hzR
          · simp [SingletonAvail]
          · exact hnow hzR)
      · refine Or.inr ⟨y, hqy, ?_⟩
        have hsub :
            (Set.insert q R \ SingletonAvail q) ⊆
              (R \ SingletonAvail q) := by
          intro z hz
          rcases hz.1 with rfl | hzR
          · exact False.elim (hz.2 (by simp [SingletonAvail]))
          · exact ⟨hzR, hz.2⟩
        exact jointRecoverable_downward n y hrest hsub

/-- Joint recoverability transports backwards along any finite directed
reachability witness.  The horizon may increase by the path length, but remains
finite. -/
theorem reachable_transport_jointRecoverable
    {X : Type*} {Step : X → X → Prop}
    {x y : X}
    (hxy : StateReachable Step x y)
    {H : ℕ} {R : Set X}
    (hR : JointRecoverable SingletonAvail Step H y R) :
    ∃ H', JointRecoverable SingletonAvail Step H' x R := by
  induction hxy with
  | refl =>
      exact ⟨H, hR⟩
  | @tail b c hxb hbc ih =>
      have hrest :
          JointRecoverable SingletonAvail Step H c
            (R \ SingletonAvail b) :=
        jointRecoverable_downward H c hR Set.diff_subset
      have hb :
          JointRecoverable SingletonAvail Step (H + 1) b R :=
        Or.inr ⟨c, hbc, hrest⟩
      exact ih hb

/-- Sufficiency half of the state-goal SCC-chain characterization:
individual reachability together with pairwise comparability implies one finite
common trajectory that visits the whole finite bundle. -/
theorem eventual_stateGoal_chain_implies_feasible
    {X : Type*} [DecidableEq X]
    {Step : X → X → Prop}
    {x : X} {F : Finset X}
    (hreach : ∀ q, q ∈ F → StateReachable Step x q)
    (hpair : PairwiseComparableOn (StateReachable Step) F) :
    HasFiniteJointRecoveryDepth SingletonAvail Step x F := by
  classical
  have aux :
      ∀ n : ℕ, ∀ (F : Finset X) (x : X),
        F.card = n →
        (∀ q, q ∈ F → StateReachable Step x q) →
        PairwiseComparableOn (StateReachable Step) F →
        HasFiniteJointRecoveryDepth SingletonAvail Step x F := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
        intro F x hcard hreach hpair
        by_cases hFempty : F = ∅
        · subst F
          exact ⟨0, by simpa [TemporalContractComplex] using
            (jointRecoverable_empty SingletonAvail Step 0 x)⟩
        · have hne : F.Nonempty := Finset.nonempty_iff_ne_empty.mpr hFempty
          rcases exists_reach_source_of_pairwise
              (Step := Step) hne hpair with ⟨q, hqF, hqall⟩
          let G : Finset X := F.erase q
          have hGcardlt : G.card < n := by
            have hlt : (F.erase q).card < F.card :=
              Finset.card_erase_lt_of_mem hqF
            simpa [G, hcard] using hlt
          have hpairG :
              PairwiseComparableOn (StateReachable Step) G := by
            intro a ha b hb hab
            exact hpair a (Finset.mem_of_mem_erase ha)
              b (Finset.mem_of_mem_erase hb) hab
          have hreachG :
              ∀ r, r ∈ G → StateReachable Step q r := by
            intro r hr
            exact hqall r (Finset.mem_of_mem_erase hr)
          have hGfinite :
              HasFiniteJointRecoveryDepth SingletonAvail Step q G := by
            exact ih G.card hGcardlt G q rfl hreachG hpairG
          rcases hGfinite with ⟨HG, hGj⟩
          have hFset :
              (Set.insert q (↑G : Set X)) = (↑F : Set X) := by
            ext z
            simp [G, hqF]
          have hFq :
              JointRecoverable SingletonAvail Step HG q (↑F : Set X) := by
            rw [← hFset]
            exact jointRecoverable_insert_current hGj
          have hxq : StateReachable Step x q := hreach q hqF
          rcases reachable_transport_jointRecoverable hxq hFq with
            ⟨HF, hFx⟩
          exact ⟨HF, hFx⟩
  exact aux F.card F x rfl hreach hpair

/-- Exact state-goal chain characterization for the eventual INSACERMO
joint-recovery semantics. -/
theorem eventual_stateGoal_feasible_iff_chain
    {X : Type*} [DecidableEq X]
    {Step : X → X → Prop}
    {x : X} {F : Finset X} :
    HasFiniteJointRecoveryDepth SingletonAvail Step x F ↔
      (∀ q, q ∈ F → StateReachable Step x q) ∧
        PairwiseComparableOn (StateReachable Step) F := by
  constructor
  · exact eventual_stateGoal_feasible_implies_chain
  · rintro ⟨hreach, hpair⟩
    exact eventual_stateGoal_chain_implies_feasible hreach hpair

end StructuralAuditReachability

end InsacermoActionabilityInformation
