import InsacermoActionabilityInformation.Decomposition
import InsacermoActionabilityInformation.BiMonotone
import InsacermoActionabilityInformation.ObstructionCertificates
import InsacermoActionabilityInformation.ContractFactorization
import InsacermoActionabilityInformation.MaximalFeasibility
import InsacermoActionabilityInformation.WeightedHittingActionability
import InsacermoActionabilityInformation.CapabilityInformationPrice
import InsacermoActionabilityInformation.CapabilityComplementarity
import InsacermoActionabilityInformation.CapabilityGainNonSubmodular
import InsacermoActionabilityInformation.FiberCommonActions
import InsacermoActionabilityInformation.HigherOrderObstructions
import InsacermoActionabilityInformation.HypergraphActionability
import InsacermoActionabilityInformation.SignedTopologicalDepth
import InsacermoActionabilityInformation.SignedTopologicalSubcontracts
import InsacermoActionabilityInformation.SignedTopologicalDepthExact
import InsacermoActionabilityInformation.SignedTopologicalMinimal
import InsacermoActionabilityInformation.ObstructionRankLocalAudit
import InsacermoActionabilityInformation.ContractAuditBridges
import InsacermoActionabilityInformation.SafeRepAuditBridge
import InsacermoActionabilityInformation.FutureEnvelope
import InsacermoActionabilityInformation.FutureDebt
import InsacermoActionabilityInformation.FutureConservationPlanner
import InsacermoActionabilityInformation.TemporalRecoverabilityEnvelope
import InsacermoActionabilityInformation.RecoveryDepthIrreversibility
import InsacermoActionabilityInformation.DecisionSemantics
import InsacermoActionabilityInformation.FutureRobustness
import InsacermoActionabilityInformation.RecoveryDebtArea
import InsacermoActionabilityInformation.TemporalJointContractComplex
import InsacermoActionabilityInformation.TemporalObstructionPersistence
import InsacermoActionabilityInformation.TemporalJointFutureRisk
import InsacermoActionabilityInformation.FutureDepthSpectrum
import InsacermoActionabilityInformation.FutureDepthBellman
import InsacermoActionabilityInformation.FutureTransformationCalculus
import InsacermoActionabilityInformation.FutureTransformationComposition
import InsacermoActionabilityInformation.EventualFutureGeometry
import InsacermoActionabilityInformation.EventualObstructionRank
import InsacermoActionabilityInformation.FutureRepairPrice
import InsacermoActionabilityInformation.UnknownFutureRobustness
import InsacermoActionabilityInformation.UnknownFutureRisk
import InsacermoActionabilityInformation.FutureRiskDecision

import InsacermoActionabilityInformation.RepairPlanDuality

import InsacermoActionabilityInformation.MasterClosureV1

import InsacermoActionabilityInformation.StructuralAuditKernel

import InsacermoActionabilityInformation.StructuralAuditSCCBridge

import InsacermoActionabilityInformation.StructuralAuditReachability

-- Structural audit E2E integration trigger: theorem layer unchanged.

-- Email-Eu-core structural audit CI trigger; theorem statements unchanged.

-- Wiki-Vote structural audit CI trigger; theorem statements unchanged.

-- Created pair-incomparability stress-test CI trigger; theorem statements unchanged.

-- France rail structural audit CI trigger; theorem statements unchanged.

-- Passenger-weighted France rail audit CI trigger; theorem statements unchanged.

-- France sovereign finance V1 CI trigger; theorem statements unchanged.

-- France sovereign finance investment-return V2 CI trigger; theorem statements unchanged.

-- France sovereign finance marginal-return V3 CI trigger; theorem statements unchanged.

-- France rail capability-finance bridge V4 CI trigger; theorem statements unchanged.

-- Retry V4 after transient GitHub/Elan 504; theorem statements unchanged.

-- France rail investment envelope frontier V5 CI trigger; theorem statements unchanged.

-- France fiscal trajectory rail V6 CI trigger; theorem statements unchanged.

-- France human capability baseline V0.2 CI trigger; theorem statements unchanged.
