import InsacermoV13Kernel.ActionabilityGeometry

namespace InsacermoV13Kernel

universe u

/-- Upward closure generated by a seed family in an abstract resource order. -/
def GeneratedUpper {P : Type u}
    (seed : P → Prop) (le : P → P → Prop) (p : P) : Prop :=
  ∃ a, seed a ∧ le a p

/-- A predicate is upward closed for the declared resource order. -/
def UpperClosed {P : Type u}
    (U : P → Prop) (le : P → P → Prop) : Prop :=
  ∀ ⦃p q : P⦄, U p → le p q → U q

/-- Minimality inside a generated upper region, modulo resource equivalence. -/
def MinimalGenerated {P : Type u}
    (seed : P → Prop) (le : P → P → Prop) (p : P) : Prop :=
  GeneratedUpper seed le p ∧
    ∀ ⦃q : P⦄, GeneratedUpper seed le q → le q p → le p q

/-- Antichain condition modulo preorder equivalence. -/
def OrderAntichain {P : Type u}
    (seed : P → Prop) (le : P → P → Prop) : Prop :=
  ∀ ⦃a b : P⦄, seed a → seed b → le a b → le b a

theorem generatedUpper_upward
    {P : Type u}
    {seed : P → Prop} {le : P → P → Prop}
    (htrans : ∀ ⦃a b c : P⦄, le a b → le b c → le a c)
    {p q : P}
    (hp : GeneratedUpper seed le p)
    (hpq : le p q) :
    GeneratedUpper seed le q := by
  rcases hp with ⟨a, ha, hap⟩
  exact ⟨a, ha, htrans hap hpq⟩

theorem generatedUpper_iff_of_upperClosed
    {P : Type u}
    {U : P → Prop} {le : P → P → Prop}
    (hrefl : ∀ p : P, le p p)
    (hupper : UpperClosed U le)
    {p : P} :
    GeneratedUpper U le p ↔ U p := by
  constructor
  · rintro ⟨a, ha, hap⟩
    exact hupper ha hap
  · intro hp
    exact ⟨p, hp, hrefl p⟩

namespace FrontierRealization

/-- One-world observation: all geometry is carried by the resource order. -/
def obs : Unit → Unit := fun _ => ()

/-- An action is available at p exactly when it is a seed resource below p. -/
def availableAt {P : Type u}
    (seed : P → Prop) (le : P → P → Prop) (p : P) : P → Prop :=
  fun a => seed a ∧ le a p

/-- The single world accepts every action; feasibility is therefore exactly
    the existence of an available seed resource below p. -/
def admissible {P : Type u} : Unit → P → Prop :=
  fun _ _ => True

/-- Exact realization lemma: a generated upper region is an INSACERMO
    GlobalSafe region of a one-world system. -/
theorem globalSafe_iff_generatedUpper
    {P : Type u}
    {seed : P → Prop} {le : P → P → Prop} {p : P} :
    GlobalSafe obs (availableAt seed le p) admissible ↔
      GeneratedUpper seed le p := by
  constructor
  · intro h
    have hs := h ()
    rcases hs with ⟨a, ha, hall⟩
    exact ⟨a, ha.1, ha.2⟩
  · rintro ⟨a, ha, hap⟩
    intro x
    refine ⟨a, ⟨ha, hap⟩, ?_⟩
    intro y hy
    exact True.intro

/-- Universality of monotone feasibility:
    every upward-closed predicate on an abstract resource order is exactly
    realizable as INSACERMO safety of a one-world system. -/
theorem arbitrary_upper_region_realizable
    {P : Type u}
    {U : P → Prop} {le : P → P → Prop}
    (hrefl : ∀ p : P, le p p)
    (hupper : UpperClosed U le)
    {p : P} :
    GlobalSafe obs (availableAt U le p) admissible ↔ U p := by
  rw [globalSafe_iff_generatedUpper]
  exact generatedUpper_iff_of_upperClosed hrefl hupper

end FrontierRealization

/-- Every antichain generator is a minimal frontier point of its upper closure. -/
theorem antichain_seed_is_minimal
    {P : Type u}
    {seed : P → Prop} {le : P → P → Prop}
    (hrefl : ∀ p : P, le p p)
    (htrans : ∀ ⦃a b c : P⦄, le a b → le b c → le a c)
    (hanti : OrderAntichain seed le)
    {a : P}
    (ha : seed a) :
    MinimalGenerated seed le a := by
  refine ⟨⟨a, ha, hrefl a⟩, ?_⟩
  intro q hq hqa
  rcases hq with ⟨b, hb, hbq⟩
  have hba : le b a := htrans hbq hqa
  have hab : le a b := hanti hb ha hba
  exact htrans hab hbq

/-- Conversely, every minimal point of a generated upper region is equivalent,
    in the resource preorder, to one of its generators. -/
theorem minimal_generated_equiv_seed
    {P : Type u}
    {seed : P → Prop} {le : P → P → Prop}
    (hrefl : ∀ p : P, le p p)
    {p : P}
    (hp : MinimalGenerated seed le p) :
    ∃ a, seed a ∧ le a p ∧ le p a := by
  rcases hp.1 with ⟨a, ha, hap⟩
  have haUpper : GeneratedUpper seed le a :=
    ⟨a, ha, hrefl a⟩
  have hpa : le p a := hp.2 haUpper hap
  exact ⟨a, ha, hap, hpa⟩

/-- Frontier representation theorem:
    an antichain generates precisely the minimal equivalence classes of its
    upward closure, and that entire upper closure has an exact INSACERMO
    one-world realization. -/
theorem antichain_frontier_representation
    {P : Type u}
    {seed : P → Prop} {le : P → P → Prop}
    (hrefl : ∀ p : P, le p p)
    (htrans : ∀ ⦃a b c : P⦄, le a b → le b c → le a c)
    (hanti : OrderAntichain seed le) :
    (∀ ⦃a : P⦄, seed a → MinimalGenerated seed le a) ∧
    (∀ ⦃p : P⦄, MinimalGenerated seed le p →
      ∃ a, seed a ∧ le a p ∧ le p a) ∧
    (∀ p : P,
      GlobalSafe FrontierRealization.obs
        (FrontierRealization.availableAt seed le p)
        FrontierRealization.admissible ↔
      GeneratedUpper seed le p) := by
  refine ⟨?_, ?_, ?_⟩
  · intro a ha
    exact antichain_seed_is_minimal hrefl htrans hanti ha
  · intro p hp
    exact minimal_generated_equiv_seed hrefl hp
  · intro p
    exact FrontierRealization.globalSafe_iff_generatedUpper

/-- Local square submodularity of a gain function. -/
def SquareSubmodular (g0 gu gv guv : Nat) : Prop :=
  g0 + guv ≤ gu + gv

/-- The already kernel-verified strict synergy witness violates diminishing
    returns: its right-to-forget gain is not submodular on the capability square. -/
theorem strict_synergy_not_submodular :
    ¬ SquareSubmodular
      (ForgetDividend 2 2)
      (ForgetDividend 2 2)
      (ForgetDividend 2 2)
      (ForgetDividend 2 1) := by
  change ¬ (1 ≤ 0)
  exact Nat.not_succ_le_zero 0

end InsacermoV13Kernel
