import InsacermoV13Kernel.FamilySeparatorDecomposition

#print axioms InsacermoV13Kernel.familySeparatorObs_eq_implies_context_eq
#print axioms InsacermoV13Kernel.globalSafe_family_separator_iff
#print axioms InsacermoV13Kernel.globalSafe_fin_family_separator_iff
#print axioms InsacermoV13Kernel.globalSafe_empty_family
#print axioms InsacermoV13Kernel.globalSafe_singleton_family_iff
