import InsacermoV13Kernel.SeparatorMessages

#print axioms InsacermoV13Kernel.indexed_of_uniform
#print axioms InsacermoV13Kernel.uniformProtocol_forgets_context
#print axioms InsacermoV13Kernel.indexedProtocol_carries_context
#print axioms InsacermoV13Kernel.indexedSeparatorProtocols_compose
#print axioms InsacermoV13Kernel.uniformSeparatorProtocols_forget_context
#print axioms InsacermoV13Kernel.ContextNecessityWitness.exactContextCode_globalSafe
#print axioms InsacermoV13Kernel.ContextNecessityWitness.one_message_unsafe
#print axioms InsacermoV13Kernel.ContextNecessityWitness.min_context_messages_two
#print axioms InsacermoV13Kernel.ContextNecessityWitness.indexed_one_local_message
#print axioms InsacermoV13Kernel.ContextNecessityWitness.no_uniform_one_local_message
#print axioms InsacermoV13Kernel.ContextNecessityWitness.context_can_be_irreducible
