import InsacermoV13Kernel.RawActionabilityBridge
import InsacermoV13Kernel.InformationCapabilityFrontier

#print axioms InsacermoV13Kernel.fiberSafe_of_refinement
#print axioms InsacermoV13Kernel.Refines.trans
#print axioms InsacermoV13Kernel.fiberSafe_of_capability_expansion
#print axioms InsacermoV13Kernel.not_fiberSafe_of_alias_conflict
#print axioms InsacermoV13Kernel.no_safe_to_unsafe_under_probe
#print axioms InsacermoV13Kernel.globalSafe_of_refinement
#print axioms InsacermoV13Kernel.globalSafe_of_capability_expansion
#print axioms InsacermoV13Kernel.fiberSafe_of_contract_weakening
#print axioms InsacermoV13Kernel.globalSafe_of_contract_weakening
#print axioms InsacermoV13Kernel.safeEncoding_of_capability_expansion
#print axioms InsacermoV13Kernel.safeEncoding_of_contract_weakening
#print axioms InsacermoV13Kernel.minSafeSymbols_antitone_capability
#print axioms InsacermoV13Kernel.minSafeSymbols_monotone_contract
#print axioms InsacermoV13Kernel.fiberSafe_iff_commonAction_fiber
#print axioms InsacermoV13Kernel.not_fiberSafe_iff_obstructed_fiber
#print axioms InsacermoV13Kernel.feasiblePair_upward_information
#print axioms InsacermoV13Kernel.feasiblePair_upward_capability
#print axioms InsacermoV13Kernel.RightToForgetWitness.strict_right_to_forget_witness
#print axioms InsacermoV13Kernel.CapabilityComplementarityWitness.capability_complementarity_exists
